name: task_management_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animated_splash_screen: ^1.3.0
  app_links: ^6.4.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_native_splash: ^2.4.5
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  go_router: ^14.8.1
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/To-do splash.json
    - assets/to-do-high-resolution-logo-transparent.png
    - assets/monogramhq.png
